-- Create skills table with Supabase conventions if it doesn't exist
CREATE TABLE IF NOT EXISTS skills (
    id SERIAL PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- Create recommended_skills table with Supabase conventions if it doesn't exist
CREATE TABLE IF NOT EXISTS recommended_skills (
    id SERIAL PRIMARY KEY,
    skill_name VARCHAR(100) NOT NULL,
    field VARCHAR(50) NOT NULL,
    priority INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(skill_name, field)
);
-- Insert common skills data with consistent naming
INSERT INTO skills (skill_name, category)
VALUES -- Programming Languages
    ('JavaScript', 'programming_languages'),
    ('TypeScript', 'programming_languages'),
    ('Python', 'programming_languages'),
    ('Java', 'programming_languages'),
    ('C#', 'programming_languages'),
    ('C++', 'programming_languages'),
    ('Ruby', 'programming_languages'),
    ('PHP', 'programming_languages'),
    ('Swift', 'programming_languages'),
    ('Kotlin', 'programming_languages'),
    ('Go', 'programming_languages'),
    ('Rust', 'programming_languages'),
    -- Web Technologies
    ('HTML', 'web_technologies'),
    ('CSS', 'web_technologies'),
    ('React', 'web_technologies'),
    ('Angular', 'web_technologies'),
    ('Vue', 'web_technologies'),
    ('Next.js', 'web_technologies'),
    ('Node.js', 'web_technologies'),
    ('Express', 'web_technologies'),
    ('Django', 'web_technologies'),
    ('Flask', 'web_technologies'),
    ('Spring Boot', 'web_technologies'),
    ('REST API', 'web_technologies'),
    ('GraphQL', 'web_technologies'),
    ('WordPress', 'web_technologies'),
    ('WebSockets', 'web_technologies'),
    ('TailwindCSS', 'web_technologies'),
    -- Databases
    ('SQL', 'databases'),
    ('MySQL', 'databases'),
    ('PostgreSQL', 'databases'),
    ('MongoDB', 'databases'),
    ('SQLite', 'databases'),
    ('Oracle', 'databases'),
    ('Firebase', 'databases'),
    ('Redis', 'databases'),
    ('Elasticsearch', 'databases'),
    ('DynamoDB', 'databases'),
    ('Cassandra', 'databases'),
    ('MariaDB', 'databases'),
    ('Neo4j', 'databases'),
    -- Cloud Platforms
    ('AWS', 'cloud_platforms'),
    ('Azure', 'cloud_platforms'),
    ('Google Cloud', 'cloud_platforms'),
    ('Heroku', 'cloud_platforms'),
    ('DigitalOcean', 'cloud_platforms'),
    ('Vercel', 'cloud_platforms'),
    ('Netlify', 'cloud_platforms'),
    ('Docker', 'cloud_platforms'),
    ('Kubernetes', 'cloud_platforms'),
    -- Data Science
    ('Machine Learning', 'data_science'),
    ('Data Analysis', 'data_science'),
    ('NumPy', 'data_science'),
    ('Pandas', 'data_science'),
    ('Matplotlib', 'data_science'),
    ('Scikit-learn', 'data_science'),
    ('TensorFlow', 'data_science'),
    ('PyTorch', 'data_science'),
    ('R', 'data_science'),
    ('Data Visualization', 'data_science'),
    ('Statistics', 'data_science'),
    ('NLP', 'data_science'),
    ('Computer Vision', 'data_science'),
    -- Tools
    ('Git', 'tools'),
    ('GitHub', 'tools'),
    ('GitLab', 'tools'),
    ('Jira', 'tools'),
    ('Confluence', 'tools'),
    ('Jenkins', 'tools'),
    ('CircleCI', 'tools'),
    ('Travis CI', 'tools'),
    ('Ansible', 'tools'),
    ('Terraform', 'tools'),
    ('Figma', 'tools'),
    ('Sketch', 'tools'),
    ('Adobe XD', 'tools'),
    ('Postman', 'tools'),
    ('Swagger', 'tools') ON CONFLICT (skill_name) DO NOTHING;
-- Insert recommended skills data
INSERT INTO recommended_skills (skill_name, field, priority)
VALUES -- Software Development
    ('Docker', 'Software Development', 10),
    ('Kubernetes', 'Software Development', 9),
    ('TypeScript', 'Software Development', 8),
    ('AWS', 'Software Development', 7),
    ('CI/CD', 'Software Development', 6),
    ('NoSQL', 'Software Development', 5),
    ('Microservices', 'Software Development', 4),
    ('Design Patterns', 'Software Development', 3),
    ('Unit Testing', 'Software Development', 2),
    ('GraphQL', 'Software Development', 1),
    -- Web Development
    ('TypeScript', 'Web Development', 10),
    ('Next.js', 'Web Development', 9),
    ('Redux', 'Web Development', 8),
    ('GraphQL', 'Web Development', 7),
    ('Docker', 'Web Development', 6),
    ('AWS', 'Web Development', 5),
    ('Jest', 'Web Development', 4),
    ('Tailwind CSS', 'Web Development', 3),
    ('WebSockets', 'Web Development', 2),
    ('PWA', 'Web Development', 1),
    -- Data Science
    ('TensorFlow', 'Data Science', 10),
    ('PyTorch', 'Data Science', 9),
    ('Scikit-learn', 'Data Science', 8),
    ('Big Data', 'Data Science', 7),
    ('Data Visualization', 'Data Science', 6),
    ('SQL', 'Data Science', 5),
    ('R', 'Data Science', 4),
    ('Spark', 'Data Science', 3),
    ('Hadoop', 'Data Science', 2),
    ('Tableau', 'Data Science', 1),
    -- DevOps
    ('Kubernetes', 'DevOps', 10),
    ('Terraform', 'DevOps', 9),
    ('AWS', 'DevOps', 8),
    ('Ansible', 'DevOps', 7),
    ('CI/CD', 'DevOps', 6),
    ('Monitoring', 'DevOps', 5),
    ('Grafana', 'DevOps', 4),
    ('Prometheus', 'DevOps', 3),
    ('Security', 'DevOps', 2),
    ('Infrastructure as Code', 'DevOps', 1),
    -- Mobile Development
    ('React Native', 'Mobile Development', 10),
    ('Flutter', 'Mobile Development', 9),
    ('Swift', 'Mobile Development', 8),
    ('Kotlin', 'Mobile Development', 7),
    ('Firebase', 'Mobile Development', 6),
    ('Mobile UI', 'Mobile Development', 5),
    ('Offline Storage', 'Mobile Development', 4),
    ('Push Notifications', 'Mobile Development', 3),
    ('Authentication', 'Mobile Development', 2),
    ('App Analytics', 'Mobile Development', 1) ON CONFLICT (skill_name, field) DO NOTHING;